#!/usr/bin/env bash
# A script that displays a list of currently running processes
# Must shor all processes , all users , including with no TTY
# Display in a user- oriented format
# Show process hierarchy/
ps -auxf
