#!/usr/bin/env bash
# ten times using if statement in the 9th iteration

COUNTER=0
while [ "$COUNTER" -lt 10 ]; do
	echo "Best School"
	if [ "$COUNTER" -eq 8 ]
	then
	    echo "Hi"
	fi
	let COUNTER=COUNTER+1
done
