#!/usr/bin/env bash
# loop from 1 to 10
#+ "bad luck" 4th
#+ "good luck" 8th
#+ "Best School" for others

COUNTER=1
while [ "$COUNTER" -le 10 ]; do
    if [ $COUNTER -eq 4 ]; then
	echo "bad luck"
    elif [ $COUNTER -eq 8 ]; then
	echo "good luck"
    else
	echo "Best School"
    fi
    let COUNTER=COUNTER+1
done
