#!/usr/bin/env bash
# displays the numbers 1 to 20
#+ "bad luck from China" after 4th
#+ "bad luck from Japan" the 9th
#+ "bad luck from Italy" after 17th

COUNTER=1
while [ "$COUNTER" -le 20 ]; do
    echo "$COUNTER"
    case "$COUNTER" in
	4)
	    echo "bad luck from China"
	    ;;
	9)
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo "bad luck from Italy"
	    ;;
    esac
    let COUNTER=COUNTER+1
done
