#!/usr/bin/env bash
# time around 12 59

HOUR=0
while [ "$HOUR" -lt 13 ]; do
    echo "Hour: $HOUR"
    MINUTE=1
    while [ "$MINUTE" -lt 60 ]; do
	echo "$MINUTE"
	let MINUTE=MINUTE+1
    done
    let HOUR=HOUR+1
done
